version: '2'
services:
  app:
    build: .
    image: imagewrangler
    container_name: imagewrangler
    volumes:
      - .:/apps/imagewrangler
    command: ["bundle", "exec", "guard"]
    tty: true
