version: '3'
services:
  httpserver:
    image: httpd:latest
    container_name: httpserver
    volumes:
      - ./test/fixtures:/usr/local/apache2/htdocs/images
    ports:
      - '80:80'
    expose:
      - '80'
    platform: linux/amd64
  app:
    build: .
    image: imagewrangler
    container_name: imagewrangler
    depends_on:
      - httpserver
    environment:
      - httpserver=http://httpserver
    volumes:
      - .:/apps/imagewrangler
    command: ["bundle", "exec", "guard"]
    tty: true
